name: gasouza-inception

networks:
  app-network:
    driver: bridge

volumes:
  app-files:
    name: app-files
    external: false  # criar volume externo
  db-files:
    name: db-files
    external: false  # criar volume externo

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - app-network
    volumes:
      - app-files:/app
    depends_on:
      - wordpress
      - mariadb
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    environment:
      - WORDPRESS_SITE_HOST
      - WORDPRESS_SITE_NAME
      - WORDPRESS_ADMIN_USER
      - WORDPRESS_ADMIN_PASS
      - WORDPRESS_ADMIN_MAIL
      - WORDPRESS_DB_NAME
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASS
    networks:
      - app-network
    volumes:
      - app-files:/app
    depends_on:
      - mariadb
    restart: always

  mariadb:
    stdin_open: true # docker run -i
    tty: true  
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - app-network
    volumes:
      - db-files:/var/lib/mysql
    restart: always