name: gasouza_inception

networks:
  app-network:
    driver: bridge

volumes:
  app-files:
    name: app-files
    external: true
  db-files:
    name: db-files
    external: true

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - app-network
    volumes:
      - app-files:/app
    depends_on:
      - wordpress
      - mariadb
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    environment:
      - WP_SITE_HOST
      - WP_SITE_NAME
      - WP_ADMIN_USER
      - WP_ADMIN_PASS
      - WP_ADMIN_MAIL
      - WP_EDITOR_USER
      - WP_EDITOR_PASS
      - WP_EDITOR_MAIL
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASS
    networks:
      - app-network
    volumes:
      - app-files:/app
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    environment:
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASS
      - DATABASE_ROOT_PASS
    networks:
      - app-network
    volumes:
      - db-files:/var/lib/mysql
    restart: always