name: gasouza-inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    external: false  # criar volume externo

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/app
    depends_on:
      - wordpress
      - mariadb
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress:/app
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: db-root-pass
        MYSQL_USER: db-user
        MYSQL_PASSWORD: db-pass
        MYSQL_DATABASE: db-wp